jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

spring:
  application:
    name: apiuser
  datasource:
    url: ENC(DVPWrsV6Iqv9egwc3jNGySGG5gkEewxG+I5X83DKxETVD1gNORn0NdFK2Z+v0u1X4SjPfzwlBvFJbqVNuMqOUicVxwsjFWgGb7b3pAQxYm0=)
    username: ENC(XhGT41xwg0J9hSXkV9tPjQ==)
    password: ENC(cOWaniGDoCFEXR9v+wRBVEwsJ5Hg6vQN)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

auth:
  service:
    url: http://localhost:8080